import = [
	"~/.config/alacritty/themes/themes/carbonfox.toml"
]
shell = { program = "/bin/zsh", args = [] }
live_config_reload = true

[window]
opacity = 0.88
dimensions = { columns = 80, lines = 30 }
padding = { x = 0, y = 0 }

[font]
normal = { family = "Fura Code Nerd Font Mono", style = "Regular" }
italic = { family = "Fura Code Nerd Font Mono", style = "Regular" }
bold = { family = "Fura Code Nerd Font Mono", style = "Regular" }
bold_italic = { family = "Fura Code Nerd Font Mono", style = "Regular" }
size = 10
